### ISSUE TITLE
Failed to change the language interface (all OS and web) v2.1.0a23

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#104]
1 - Go to the application.
2 - Go to the crowdfunding / catalog of projects and click on any project.
3 - In the project to switch the interface language.
**Result:** Error.

![naylbl5ux4edv2](https://cloud.githubusercontent.com/assets/10295842/13703684/4fd9f6a2-e7a0-11e5-97ba-4b72ebda096d.jpg)

1 - Зайти в приложение.
2 - Перейти на CrowdFunding / Каталог проектов и кликнуть на любой проект.
3 - В открывшемся проекте переключить язык интерфейса.
**Результат:** Ошибка.

**Comment by gentee** [comment]
Fixed by commit #137

**Comment by ylomakin** [comment]
Fixed
