### ISSUE TITLE
Login does not happen (Microsoft Edge)

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#107]
1 - Go to the pull.
2 - Press Enter, select the key and enter the password, press Enter.
**Result:** There is a reload of the page as in the normal input, but misses to the Login / Register page, sign-in occurs.

1 - Зайти на пулл.
2 - Нажать кнопку Войти, выбрать ключ и ввести пароль, нажать Enter.
**Результат:** Происходит перезагрузка страницы как при нормальном входе, но попадает на страницу Войти/Зарегистрироваться, вход в аккаунт не происходит.

**Comment by c-darwin** [comment]
Повторить баг не смог. Взял новый ключ, установил пароль, всё входит нормально.
