### ISSUE TITLE
Сrowdfunding - bug counter (Windows 10) v2.2.1b1

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#115]
1 - Go to the crowdfunding / My Projects.
2 - Open every funded project.
**Result:** The number of errors are created (and perhaps can not be created by one person?) And financed the project.

![zrjodons1z3xmm](https://cloud.githubusercontent.com/assets/10295842/13775787/43c1f560-eaaf-11e5-84d5-3fa67d6152a5.jpg)

1 - Зайти в CrowdFunding / Мои проекты.
2 - Открыть любой профинансированный проект.
**Результат:** Ошибка количества создавших (а разве может быть создавший не один человек?) и профинансированных данный проект.

**Comment by gentee** [comment]
Похоже были изменения. Нужно заново проверять.

**Comment by ylomakin** [comment]
Понял, это не кол-во людей, создавших проект, а кол-во проектов, созданных юзером.
Закрываю.Понял, это не кол-во людей, создавших проект, а кол-во проектов, созданных юзером.
Закрываю.
