### ISSUE TITLE
Not selected key

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#117]
1 - Go to http://e.dcoin.club/
2 - Click the top menu on the Key.
3 - In the pop-press the Select key, and select a key dialog box.
**Result:** Not selected key.

1 - Зайти на http://e.dcoin.club/
2 - Нажать в верхнем меню на Key.
3 - Во всплывающем диалоговом окне нажать кнопку Выберите ключ и выбрать ключ.
**Результат:** Не выбирается ключ.

**Comment by c-darwin** [comment]
https://github.com/democratic-coin/dcoin-go/commit/d6b69131cc4b09b6df1b772cf132cd04ff2c23eb

**Comment by ylomakin** [comment]
Fixed
