### ISSUE TITLE
Bug upgrades (Windows 7)

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#122]
1 - Start the app and log in.
2 - On the main page, click on the installation of a new version.
**Result:** The program is restarted before the new version is not updated. It remains hanging preloader.

![8an5p58cqxalv2](https://cloud.githubusercontent.com/assets/10295842/13875876/21d57b14-ed09-11e5-9c8b-bab4c3ec5283.jpg)

1 - Запустить и войти в приложение.
2 - На главной странице нажать на кнопку установки новой версии.
**Результат:** Программа перезапускается, до новой версии не обновляется. Остаётся висеть прелоадер.

**Comment by ylomakin** [comment]
Чуть чуть изменилась последовательность, но не работает всё равно.
После нажатия обновить, обновляется и появляется надпись complete.
Но программа не перезагружается, остаётся висеть та же версия, из которой делалось обновление.
На скринах пошагово наглядно показал.

![13-04-2016 15-58-17](https://cloud.githubusercontent.com/assets/10295842/14493948/f0db6824-0190-11e6-928a-63ed7fa50826.jpg)
![13-04-2016 15-56-54](https://cloud.githubusercontent.com/assets/10295842/14493949/f2d96a54-0190-11e6-98b8-6f3b244d5f95.jpg)
![13-04-2016 15-58-37](https://cloud.githubusercontent.com/assets/10295842/14493951/f4679b20-0190-11e6-8b10-11e196b87539.jpg)

**Comment by ylomakin** [comment]
Обновление работает, но после перезагрузки не исчезает прелоадер, так и продолжает висеть.

**Comment by gentee** [comment]
Исправлено с удалением loader в #222

**Comment by ylomakin** [comment]
Лоадер снова остаётся.
И у лоадера появились полосы прокрутки #225

**Comment by gentee** [comment]
Вроде исправил в #279, у меня по-крайней мере сейчас нормально работает. При проверке обновления нужно чтобы скачивался уже новый исправленный файл.

**Comment by ylomakin** [comment]
Сейчас вообще не обновляется.
Перезапускается и висит это окно
![03-06-2016 15-52-55](https://cloud.githubusercontent.com/assets/10295842/15779189/86450246-29a3-11e6-95a5-35997d143958.jpg)

И набито куча процессов
![03-06-2016 15-55-30](https://cloud.githubusercontent.com/assets/10295842/15779208/a0f1d3e4-29a3-11e6-8f5e-ff342cb66734.jpg)

**Comment by gentee** [comment]
Это после Loader или это и есть Loader?

**Comment by ylomakin** [comment]
Нет, после Loader

**Comment by gentee** [comment]
Исправления внесены в коммит #312. Нужно будет потестировать.

**Comment by ylomakin** [comment]
Fixed
