### ISSUE TITLE
Bug upgrades (Ubuntu 15.10)

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#124]
1 - Start the app and log in.
2 - On the main page, click on the installation of a new version.
**Result:** The program does not restart, a new window opens to the new version is not updated. It remains hanging preloader.

![kaxdbdqu4ledma](https://cloud.githubusercontent.com/assets/10295842/13876082/606d0030-ed0a-11e5-90ab-a6fe49de9938.jpg)

1 - Запустить и войти в приложение.
2 - На главной странице нажать на кнопку установки новой версии.
**Результат:** Программа не перезапускается, открывается новое окно, до новой версии не обновляется. Остаётся висеть прелоадер.

**Comment by gentee** [comment]
Нужно перепроверить, так как исправлялся подобный баг.

**Comment by ylomakin** [comment]
А у прелоадера возможно убрать кнопки закрыть/свернуть?
Как вот на скрине выше, вообще без рамки окна?

**Comment by gentee** [comment]
Это я добавлял заголовок окна и рамки, почему, что-то я уже не помню сейчас. Может из-за того, что он тогда оставался и чтобы была возможность закрыть его. Можно попробовать конечно снова убрать рамку.

**Comment by gentee** [comment]
Поднял историю сейчас по этому вопросу. Там если без рамки, то на удаленном сервере на Windows 7 программа запускается через раз. Поэтому и сделал рамку. Это какой-то баг у самого thrust_shell на чистой Windows 7, так как их пример без рамки также вылетал.

**Comment by ylomakin** [comment]
А если не долго и не сложно, можно убрать кнопки или сделать disabled, как встречается у приложений? Чтобы нельзя было закрыть или растянуть окно.

**Comment by gentee** [comment]
По умолчанию таких опций в thrust_shell нет, но можно сделать, чтобы рамка показывалась только на Windows 7.

**Comment by gentee** [comment]
Я добавил в коммите #294 проверку на Windows 7. Сейчас только на ней loader будет с рамкой.

**Comment by ylomakin** [comment]
Fixed
