### ISSUE TITLE
You can not go to My Account (all OS and web) v2.2.3a4

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#128]
1 - Go to My Account and add two trusted arbitrator.
2 - Go to any page, and then click in the menu go to My Account.
**Result:** Page does not open or are now in the application or the pool, or anywhere.
`{"error":"invalid character 'N' looking for beginning of value (controllers.(*Controller).WalletsList : 119)"}`

![kag7p7nigkl4va](https://cloud.githubusercontent.com/assets/10295842/13897791/9bef0e2a-edc6-11e5-9f83-41154898196e.jpg)

1 - Зайти в My Account и добавить два доверенных арбитра.
2 - Перейти на любую страницу, а потом кликом в меню зайти на My Account.
**Результат:** Страница не открывается теперь ни в приложении, ни на пуле, нигде.

**Comment by c-darwin** [comment]
fixed https://github.com/democratic-coin/dcoin-go/commit/ddb87dde59207e6d7c1cbe988fdf565e6ae781f5

**Comment by ylomakin** [comment]
Fixed
