### ISSUE TITLE
Очень тяжело изменить аватар

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#13]
**Windows 7 64-bit**

1 - Запустить приложение.
2 - Зайти в аккаунт, используя ключ и пароль.
3 - Перейти на Изменение имени и аватара.

**Результат:** Практически не возможно найти урл с количеством до 50 символов.

**Ожидаемый результат:** Убрать ограничение количества символов в поле Аватар или сделать ограничение больше.

**Comment by c-darwin** [comment]
https://github.com/c-darwin/dcoin-go/commit/ffd4db6fdc096485f8d1a7eb8fc1255879770483

**Comment by ylomakin** [comment]
В релизе v2.1.0a17 вот что после отправки в DC-сеть
![naylbl5ux38ov2](https://cloud.githubusercontent.com/assets/10295842/13460069/d4201170-e080-11e5-8c93-49fcd3f4f4b3.jpg)

После повторного захода на страницу в таблице транзакций следующий комент

`Error: incorrect avatar (dcparser.(*Parser).ParseDataGate : 198)`
![krd1j1ki0bre6m](https://cloud.githubusercontent.com/assets/10295842/13460145/502210f2-e081-11e5-88ee-d18e32a19bb6.jpg)

**Comment by ylomakin** [comment]
В релизе v2.2.3a5 ава и имя меняется, но вот так:
1 - после заполнения имени, урла и нажатии кнопки отправить в сеть появляется окно

![24-03-2016 11-08-19](https://cloud.githubusercontent.com/assets/10295842/14012903/b1dced1c-f1b1-11e5-9a67-131f4f2220d3.jpg)

2 - обновляем страницу или заходим на неё после перехода на любую другую, видим таблицу транзакций, и в ней идёт проверка добавления авы.
3 - после успешной проверки появляется ава, но имя не меняется

![24-03-2016 11-16-58](https://cloud.githubusercontent.com/assets/10295842/14012938/f599c246-f1b1-11e5-8982-b5148d13dd5f.jpg)

4 - после смены языка интерфейса или после выхода из приложения и повторном входе появляется имя.

![24-03-2016 11-19-15](https://cloud.githubusercontent.com/assets/10295842/14012994/485a3d1c-f1b2-11e5-9b86-d588674c8754.jpg)
