### ISSUE TITLE
Unable to create Auto payments v2.2.3a5

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#132]
1 - Go to the Auto payments.
2 - Create and send avtoplatёzh network.
**Result:** Transactions are not. Did I correctly fill in the fields, but no one says anything about the restrictions.

![c1495f32d8](https://cloud.githubusercontent.com/assets/10295842/13917461/821a0352-ef69-11e5-8558-174c73a50ad4.jpg)

1 - Зайти на Auto payments.
2 - Создать автоплатёж и отправить в сеть.
**Результат:** Транзакции не проходят. Возможно я некорректно заполняю поля, но нигде ничего не написано про ограничения.

**Comment by gentee** [comment]
Период должен быть от 86400 до 86400*365, то есть от суток до года. Может тогда период запрашивать не в секундах, а в днях? Я думаю, что нужно сделать какую-нибудь функцию, которая могла бы проверять валидность данных и показывать вменяемые сообщения. Например, есть ли такой пользователь, не пустое ли значение, входит ли значение в интервал, не превышает ли значение доступные средства и т.д. Вызывать эту функцию по ajax, если функция вернет ошибку, то показывать ее, а если всё нормально, то отправлять данные. Я думаю, такое много где может пригодиться, так как форм много и ошибки из-за неправильных начальных данных получаются не очень читаемые. Если навесить такие проверки на формы, то ошибок в транзакциях гораздо меньше было бы.

**Comment by ylomakin** [comment]
Да, проверки это будет круто.
Но период (в данном случае по крайней мере) может сделать selectbox с забитыми данными, типа 1 сутки, 2 суток, 3 суток, 1 неделя ...... 1 месяц ..... 1 год? Или набором полей (цифры, календарь и т.д.).
Кстати, а для чего нужен автоплатёж сейчас или в будущем? Оплата по типу как в банках, комуналка, страховка и тому подобное?

**Comment by gentee** [comment]
Функция проверки такая будет в ближайшее время. Автоплатеж видимо пока касается только переводов другим пользователям.

**Comment by c-darwin** [comment]
@ylomakin да, как в банках. Но сделал прежде всего, чтобы автоплатеж создавался в пользу владельцев пулов, к которым привязываются юзеры.

**Comment by gentee** [comment]
Я добавил функцию check_form (commit #141) для проверки корректности данных на форме. Пока есть только три типа проверки: на пустоту, на целочисленный интервал и на наличие пользователя. Посмотреть как это на данный момент работает можно на Автоплатеже - new_auto_payment.html.

**Comment by ylomakin** [comment]
Fixed
