### ISSUE TITLE
Credit transfer error v2.2.3a5

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#139]
1 - Create two loans from one miner (the borrower).
2 - The Credits section of the second miner (lender), press the Transfer button.
**Result:** Transaction Error, no amount of money is not transferred. If the account is not dUSD 1000 to the first request, the second request 5 dUSD there (on the account for almost 8 dUSD).

![23-03-2016 14-53-21](https://cloud.githubusercontent.com/assets/10295842/13985877/eee69712-f107-11e5-9629-d94599317562.jpg)

1 - Создать два кредита у одного майнера (заёмщика).
2 - В разделе Credits у второго майнера (кредитора) нажать кнопку Transfer.
**Результат:** Ошибка транзакции, ни одна сумма не передаётся. Если на счёте нет 1000 dUSD для первого запроса, то для второго запроса 5 dUSD есть (на счёте почти 8 dUSD).

**Comment by gentee** [comment]
Transfer - это передача выданного кредита другому кредитору. То есть, если тебе кто-то должен, то ты можешь передать этот долг другому человеку. А ты наверняка указывал в качестве UserId 1923, то есть получается что ты отдаешь долг самому заемщику - поэтому и ошибка. Но я вот, честно говоря, так и не понял как активировать кредит и передать деньги заемщику. А то сейчас получается, что заемщик, создавая кредит и указывая меня в качестве кредитора сразу получает активный кредит без всякого одобрения и передачи суммы кредита с моей стороны. Не совсем понятен смысл такого кредита.

**Comment by ylomakin** [comment]
Fixed
