### ISSUE TITLE
There is not Delete Auto-payment

### ISSUE THREAD

**Issue by gentee** [democratic-coin/dcoin-go#143]
Отсутствует удаление Автоплатежа. При попытке удаления переносимся на удаление кредита.
![auto1](https://cloud.githubusercontent.com/assets/2069001/14038188/252add0c-f26f-11e5-9d9c-e82e9021e776.png)
![auto2](https://cloud.githubusercontent.com/assets/2069001/14038191/30babd54-f26f-11e5-87c4-ff897cd51844.png)

Похоже, что для удаления автоплатежа есть только реализация в dcparser, а в controllers и templates ничего нет.

**Comment by ylomakin** [comment]
Fixed
