### ISSUE TITLE
Not running the downloaded video v2.2.3a5

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#145]
When registering miners, adding new promised amount, generally everywhere, where you can add a video file.
The file is filled, but does not work.
Tolley is just an emulation download, and the file is not filled in, or omitted Video is not converted to the correct format.
As I just do not encode video to download, it is not working.
Also, the questionnaire came confirmation of the promised amount and the registration of the new miners, anywhere video off.

![25-03-2016 09-04-21](https://cloud.githubusercontent.com/assets/10295842/14040255/fd535fd0-f26d-11e5-9621-8022c9fe8b45.jpg)

При регистрации майнера, при добавлении новой обещанной суммы, в общем везде, где можно добавить видео файлом.
Файл заливается, но не работает.
Толи это просто эмуляция загрузки и файл не заливается, толи видео не конвертируется в нужный формат.
Как я уже только не кодировал видео для загрузки, всё равно не работает.
Также приходили анкеты на подтверждение обещанной суммы и на регистрацию нового майнера, нигде видео нерабочее.

**Comment by c-darwin** [comment]
Больше деталей. Какой браузер, есть ли файл?

**Comment by ylomakin** [comment]
Данный скриншот сделан в FF45
Но видео не работает нигде вообще, ни на какой системе.
Я ещё за два месяца ни разу не видел рабочее видео (только ютубовское работает, если указывают) :)
Но учитывая глюки, которые у меня проскачили с регистрацией, просьба написать ОС и браузер (если в браузере), я ещё проверю и может будут другие выводы.

**Comment by gentee** [comment]
У меня на проверке майнеров показывался плеер (не youtube) и проигрывалось видео. Windows 10 и Опера.

**Comment by ylomakin** [comment]
Да, баг исправлен.
Баг то довольно давнешний, исправилось наверное с другими правками.
