### ISSUE TITLE
Don't run Auto payments v2.2.3a5

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#148]
1 - Start the application.
2 - Sign in to your account.
3 - Go to My account / Auto payments
4 - Create a auto payment.
**Result:** No auto payment did not load.
**Expected result:** The next day (exactly the same time when auto payment or 00-00 on the server was created) was to create a transaction, as a result of which the said amount auto payment moved up to a specified account.

![25-03-2016 10-58-23](https://cloud.githubusercontent.com/assets/10295842/14041496/2b6ba8bc-f27a-11e5-8091-10d48c861a12.jpg)

1 - Запустить приложение.
2 - Войти в аккаунт.
3 - Перейти на My account / Auto payments
4 - Создать авто платёж.
**Результат:** Ни один автоплатёж не сработал.
**Ожидаемый результат:** На следующие сутки (точно в тоже время, когда был создан автоплатёж или в 00-00 по серверу) должна была создаться транзакция, в результате которой указанная сумма автоплатежа перевелась на указанный аккаунт.

**Comment by c-darwin** [comment]
сумма же 0. надо запретить создавать с нулевой суммой

**Comment by ylomakin** [comment]
Сумма указывалась, а вот в таблице да, почему-то 0 показывает.

**Comment by gentee** [comment]
Я добавил проверку, чтобы Amount было больше нуля. Проверь, если уверен, что значение было больше нуля, а показывается в таблице 0, то пришли свою базу. У меня сколько указывал, столько и показывается в таблице.
Fixed commit #260

**Comment by ylomakin** [comment]
А автоплатёж одноразовый или если я указал день, то будет отправляться каждый день, пока не удалю?

**Comment by c-darwin** [comment]
если указал день, будет каждый день

**Comment by ylomakin** [comment]
Тогда есть баг.
Только точно не понял, жду до завтра.
Платёж отправился сегодня утром первый раз при заходе в кошелёк.
Выходит, он отрабатывает верно, но если ты онлайн. Либо он отработал с опозданием.
А создавался автоплатёж 20 мая.

**Comment by ylomakin** [comment]
Fixed
