### ISSUE TITLE
Error Auto payments v2.2.3a5

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#149]
1 - Start the application.
2 - Sign in to your account.
3 - Go to My account / Auto payments
4 - Create an auto payment as in the screenshot.
![25-03-2016 12-16-20](https://cloud.githubusercontent.com/assets/10295842/14042609/243534f0-f284-11e5-9d84-b0c44422bce8.jpg)
**Result:** After the approval of the transaction once auto payments table appears. But like all previous zero-sum. The table and the commission amount is zero.

![25-03-2016 12-18-06](https://cloud.githubusercontent.com/assets/10295842/14042614/29e6c666-f284-11e5-9cc5-ade261204234.jpg)

1 - Запустить приложение.
2 - Войти в аккаунт.
3 - Перейти на My account / Auto payments
4 - Создать автоплатёж как на скриншоте.
**Результат:** После одобрения транзакции в таблице появляется очередной автоплатёж. Но как и все предыдущие с нулевой суммой. В таблице сумма и комиссия равна нулю.

**Comment by gentee** [comment]
Fixed by commit #151

**Comment by ylomakin** [comment]
Fixed
