### ISSUE TITLE
No notification received by the job v2.2.3a5

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#154]
1 - Start the application.
2 - See the Assignments Unit.

![28-03-2016 11-12-52](https://cloud.githubusercontent.com/assets/10295842/14074966/bc6b489e-f4dd-11e5-9791-5c28dec4012b.jpg)

**Result:** In the Assignments section is 0. But if you go to the Mining / Assignments or click to **0**, sometimes there are miners profiles. Conclusion - stop getting notifications of new jobs.

![28-03-2016 11-13-40](https://cloud.githubusercontent.com/assets/10295842/14074970/c11353c8-f4dd-11e5-814e-dbe8139f645d.jpg)

1 - Запустить приложение.
2 - Посмотреть на блок Assignments.
**Результат:** В блоке Assignments стоит 0. Но если зайти на Mining / Assignments или кликнуть на **0**, то иногда появляются анкеты майнеров. Вывод - перестали приходить уведомления о новых заданиях.

**Comment by gentee** [comment]
Вносились исправления. Нужно проверить заново.

**Comment by ylomakin** [comment]
Fixed
