### ISSUE TITLE
The maximum video size should not exceed 30MB v2.2.3a5

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#157]
Максимальный размер видео не должен превышать 30Мб, иначе пулл, куда шлётся видео, выдаёт ошибку:
`05:58:39.254 type11.go:115 Type11 [ERRO]  size>32mb (tcpserver.(*TcpServer).Type11 :  115)[2.2.3a5]`

![error code](https://cloud.githubusercontent.com/assets/10295842/14075871/892501b6-f4e5-11e5-94a3-1993779365aa.png)

**Comment by gentee** [comment]
Fixed in commit #166.
Там на самом деле идет проверка на 64 МБ, а не 32, поэтому при проверке я тоже оставил предел в 64 МБ.

**Comment by ylomakin** [comment]
Fixed
