### ISSUE TITLE
Table "Comments from users that you checked" does not disappear v2.2.3a5

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#158]
1 - Install the application.
2 - Register.
3 - Complete all the steps to upgrade your account.
4 - Wait for comments from reviewers miners.
5 - Do not get approval to repeat the upgrade account.
![28-03-2016 13-12-22](https://cloud.githubusercontent.com/assets/10295842/14078898/36d7b15c-f502-11e5-82d6-1fc5384af937.jpg)

**Result:** When you re waiting for an upgrade, with commentary table does not disappear, but only supplemented with new comments.
![28-03-2016 16-18-07](https://cloud.githubusercontent.com/assets/10295842/14078908/3c432fe0-f502-11e5-8a0f-8f21d95b36cf.jpg)

1 - Установить приложение.
2 - Зарегистрироваться.
3 - Пройти все шаги апгрейда аккаунта.
4 - Дождаться комментариев от проверяющих майнеров.
5 - Не получив одобрения, повторить апгрейд аккаунта.
**Результат:** При повторном ожидании апгрейда, таблица с комментариями не исчезает, а только дополняется новыми комментариями.

**Comment by gentee** [comment]
Commit #169

**Comment by ylomakin** [comment]
Fixed
