### ISSUE TITLE
Skip loading profile

### ISSUE THREAD

**Issue by gentee** [democratic-coin/dcoin-go#160]
Сommit #159 позволяет пропускать загрузку фото в профиль пока количество майнеров меньше или равно 1000.  При этом для лучшей совместимости, в качестве фото профиля и координат скрытно дублируется основное фото и его точки. Поэтому, на данный момент, при проверке майнера в профиле будет копия основного фото.

**Comment by ylomakin** [comment]
Я не совсем понял, что и как тут проверить.
Можно подробнее?

**Comment by gentee** [comment]
Сейчас не требуется загрузки фотографии в профиль при отправки заявки в майнеры (пока < 1000 майнеров). То есть проверить, что запрашивается только фото в анфас. Ну и при проверке новых майнеров показывается только фото в анфас.

**Comment by ylomakin** [comment]
Fixed
