### ISSUE TITLE
Bug Currency exchange v2.2.3a6

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#161]
1 - Go to the Currency exchange.
2 - Buy 1 for 1 dWOCH dUSD.
**Result:** The operation was successful, dUSD debited from the account. But nowhere dWOC not appeared. In the mail came a notification `Debiting 0.01 DUSD`

![29-03-2016 15-10-57](https://cloud.githubusercontent.com/assets/10295842/14107510/56319c10-f5c1-11e5-9a9d-8750b9594593.jpg)

1 - Зайти на Currency exchange.
2 - Купить 1 dWOC за 1 dUSD.
**Результат:** Операция прошла успешно, dUSD списались со счёта. Но нигде dWOC не появились. На почту пришло такое уведомление `Debiting 0.01 DUSD`

**Comment by c-darwin** [comment]
Встречный одер вообще был? Т.е. на бирже были DWOC на продажу?
Списывается и создается ордер, который будет в "My orders"
0.01 - что это? есть подозрение что комиссия ноду, это можно понять только если увидеть блок.
Инфы мало. Скидывай номер блока, где транзакция прошла.

**Comment by ylomakin** [comment]
Ордер есть, в общем я что-то не понял, как тут менять.

![01-04-2016 12-19-03](https://cloud.githubusercontent.com/assets/10295842/14203008/11bd7f3c-f804-11e5-8d9c-17e3a614447c.jpg)

Обмена не было, создался ордер.
Да, письмо пришло снова.
**Блок - Запечатано в блоке 288880.**
![01-04-2016 12-19-17](https://cloud.githubusercontent.com/assets/10295842/14203001/034bf474-f804-11e5-8643-fcd6eaf75cec.jpg)

**Comment by c-darwin** [comment]
так проблемы нет? 1 dwoc  придет когда ордер будет удовлетворен.

**Comment by ylomakin** [comment]
1 - заполняю как на скриншоте
![13-04-2016 10-31-28](https://cloud.githubusercontent.com/assets/10295842/14485949/fecbf03a-0162-11e6-8a60-126592ef5a86.jpg)

2 - выдаёт ошибку
`Error: [ERROR] amount=0 (dcparser.(*Parser).NewForexOrderFront : 45) [sign] = 82010089fb71292db1cbfaf62670ae1aa3e1d4cc3fa533865d51a29d278fbefe5e90ea1766e217e83a62c29403844cff9e9dbf4ba8e0d09e262c27aaa4ff0623063cba93445a26e092ee4962376f9497b481d79904c8e8727a65b4`

3 - заполняю также повторно, снова ошибка, но чуть другая
`Error: [ERROR] amount=0 (dcparser.(*Parser).NewForexOrderFront : 45) [user_id] = 1792 [sell_rate] = 0.0222222222 [commission] = 0.01 [buy_currency_id] = 58 [sign] = 8201003d995781af732fd3ee03310e2478fcb6312c2e0eed394ee5ec3063adba3094de2ae4afe54c71238ac0aad993b`

![13-04-2016 10-34-55](https://cloud.githubusercontent.com/assets/10295842/14486040/898daee8-0163-11e6-9817-e80153a7ce29.jpg)
