### ISSUE TITLE
Sort messages in chat randomly v2.2.3a6

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#162]
1 - Go to the application.
2 - Send a message to the chat with one user.
3 - Send a chat message to other user.
**Result:** Messages are placed not in order of priority, as well as horrible. Different operating systems differently. When you refresh the page remain in those places where already started, ie the error is not a temporary, randomly sorted so.

![29-03-2016 16-54-33](https://cloud.githubusercontent.com/assets/10295842/14111027/bb98ee0e-f5d1-11e5-8aed-ee9b9d5662ff.jpg)

![29-03-2016 16-38-10](https://cloud.githubusercontent.com/assets/10295842/14111035/c0a1fd8c-f5d1-11e5-8d22-2a455f5d0c32.jpg)

1 - Зайти в приложение.
2 - Отправить сообщение в чат одним юзером.
3 - Отправить сообщение в чат другим юзером.
**Результат:** Сообщения расставлены не в порядке очерёдности, а как попало. В разных ОС по разному. При обновлении страницы остаются на тех местах, куда уже стали, то есть ошибка не временная, случайно так отсортировавшая.

**Comment by LincolnFaradey** [comment]
Test it one more time
