### ISSUE TITLE
Error: Reload Blockchain

### ISSUE THREAD

**Issue by gentee** [democratic-coin/dcoin-go#165]
Часто по утрам при первом запуске появляется ошибка Error: Reload Blockchain. Явной причины я пока не понял (почему остается запись в main_lock) и почему из-за этого работа невозможна. Проблема в другом - когда я нажимаю на эту кнопку, то у меня происходит загрузка с прогрессом баром в течении пары минут, а затем начинается синхронизация блокчейнов с 0. Приходится всё удалять и заново устанавливать. А что будет делать пользователь в этой ситуации? Будет ждать сутки или потеряет интерес к dcoin? 
Может стоит делать синхронизацию не с 0, а как при установке?

**Comment by c-darwin** [comment]
Если резко завершить работу приложения, то в main_lock может остаться запись о работе демона. 
Т.к. мог обрабатываться блок, то чтобы не допустить расинхронизации и пишется main_lock. 
Если была стандартная установка, то она же должна произойти после сбоя с main_lock

**Comment by gentee** [comment]
Да, делаю только стандартные установки, а после сбоя собирает с нуля. Что интересно, я постоянно обрубаю задачи, а ошибка Reload Blockchain пока появлялась только по утрам.

**Comment by c-darwin** [comment]
Там время должно пройти. 300 секунд

**Comment by gentee** [comment]
С этой ошибкой ситуация следующая.Вызывается функция ClearDb которая чистит таблицы и в том числе таблицу info_block. Демон block_collection берет из этой таблицы номер blockchain с которого следует начинать загрузку. А так как таблица пустая, то загрузка цепочки блоков начинается с нуля. При установке же мы скачиваем уже начальную готовую базу, где в таблице info_block уже прописан определенный номер.
Я пока не нашел способ как решить эту проблему. Если не удалять эту таблицу info_block, то тогда проблемы возникают у других демонов.

**Comment by c-darwin** [comment]
Если в main_lock что-то осталось при резком завершении приложения, то варианта 2: с нуля собрать из блокчейна или скачать БД mlitedb.db.
Если качать БД, то все таблицы в БД будут перезаписаны и вызов ClearDb не имеет смысла.
Если юзер не делал стандартную установку, а собирал БД с нуля, то нужен ClearDb

**Comment by gentee** [comment]
Тогда получается, нужно проверить если установка была стандартная, то просто, как при установке, скачивать базу и всё.

**Comment by c-darwin** [comment]
Да, на сколько помню, я это делал, но почему-то на срабатывает

**Comment by gentee** [comment]
Fixed in #187

**Comment by ylomakin** [comment]
Fixed
