### ISSUE TITLE
Warning private key change v2.2.3a6

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#171]
1 - Start an application or go to the pool.
2 - Add a new user.
3 - Put the key to the new user.
4 - At the entrance to the transferred key will be prompted to replace the key.
5 - Switch the key in the mode Normal mode.
**Result:** A message appears on the shift key error. But this transaction is to replace the key to successfully left the network for review. Testing took place successfully.

![31-03-2016 12-59-51](https://cloud.githubusercontent.com/assets/10295842/14173365/2aec5ef6-f746-11e5-9e77-c0f432d35388.jpg)

1 - Запустить приложение или зайти на пул.
2 - Добавить нового юзера.
3 - Передать ключ новому юзеру.
4 - При входе с переданным ключом поступит запрос на смену ключа.
5 - Сменить ключ в режиме Normal mode.
**Результат:** Появляется сообщение об ошибке смены ключа. Но при это транзакция на смену ключа успешно ушла в сеть на проверку. Проверка прошла также успешно.

**Comment by gentee** [comment]
Fixed in commit #320

**Comment by ylomakin** [comment]
Fixed
