### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by gentee** [democratic-coin/dcoin-go#172]
Возникло несколько вопросов
* daemons/common.go - func ClearDb - 291 line
	go stopdaemons.WaitStopTime()
Непонятно зачем вызывается еще одна копия этой функции. Предыдущий вызов в dcoin/dcoin.go у нас же остается рабочим и не зависит от перезапуска демонов.

* utils/sql.go - func DbLock - line 2162
```
if Time()-t > 600 {
     log.Error("%d %s %d", t, exists["script_name"], Time()-t)
     if Mobile() {
	 db.ExecSql(`DELETE FROM main_lock`)
    }
}
```
Почему для Mobile очищаем таблицу?

* Непонятна ситуация с таблицей main_lock. Функция DbLock лочит без всяких проверок на script_name, подразумевается наличие одной записи, а DbUnlock делает проверки по script_name, как будто у нас может быть несколько записей в main_lock.

**Comment by c-darwin** [comment]
Да,  go stopdaemons.WaitStopTime() похоже лишний

**Comment by c-darwin** [comment]
Надо избавиться от очищения для мобильных, т.к. это была временная мера. Но чтобы это сделать надо протестировать, что демоны успевают завершиться при переходе приложения в спящий режим на ios и на андройде

**Comment by c-darwin** [comment]
>>DbUnlock делает проверки по script_name, как будто у нас может быть несколько записей в main_lock.
Если какой-то демон сделал lock. то именно он и должен его убрать.
