### ISSUE TITLE
It is not possible to upgrade miners (OS X El Capitan 10.11.2) v2.2.3a6

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#174]
1 - Install the application and register a new key.
2 - Start the upgrade account.
**Result:** In the third step does not move to the next step. Hanging preloader and the transition does not occur.

![01-04-2016 12-38-33](https://cloud.githubusercontent.com/assets/10295842/14205017/dbc2c13c-f810-11e5-8c70-df7385474e8f.jpg)

1 - Установить приложение и зарегистрировать новый ключ.
2 - Начать апгрейд аккаунта.
**Результат:** На третьем шаге не переходит на следующий шаг. Висит прелоадер и переход не происходит.

**Comment by ylomakin** [comment]
Тоже самое на Elementary OS 0.3.2 (Linux)

![01-04-2016 15-52-28](https://cloud.githubusercontent.com/assets/10295842/14207327/0b9f5580-f822-11e5-81e5-4b5fce273b75.jpg)

**Comment by c-darwin** [comment]
пересобери и проверь, не должно быть
