### ISSUE TITLE
Geolocation - Android 5.x+

### ISSUE THREAD

**Issue by LincolnFaradey** [democratic-coin/dcoin-go#176]
I guess we need to apply new rules to our manifest

![screenshot_20160402-091130](https://cloud.githubusercontent.com/assets/3097332/14226611/72fadc08-f8b4-11e5-920c-e0c4f2650f38.png)

**Comment by c-darwin** [comment]
на 5.1 тоже есть проблема

**Comment by ylomakin** [comment]
Fixed
