### ISSUE TITLE
Bug registration (Samsung Galaxy SM-G350E Android 4.4.2, Xiaomi HM 1SLTETD Android 4.4.2, Doogee X5 Android 5.1) v2.2.3a6

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#179]
1 - Download the app, install and run.
2 - After the acquisition of blocks, click the Sign Up button.
3 - On the page that appears to refuse registration.
4 - Once again press the up.
**Result:** Up is no longer possible, is possible only after the full application removal and installation again.

![screenshot_2016-04-04-13-04-32_org golang app](https://cloud.githubusercontent.com/assets/10295842/14252065/62c98966-fa8e-11e5-97d3-89fa880f94fe.png)

![screenshot_2016-04-04-14-27-10](https://cloud.githubusercontent.com/assets/10295842/14247719/d29742d0-fa78-11e5-91f3-85fe54fd9854.png)

1 - Скачать приложение, установить и запустить.
2 - После сбора блокчейнов, нажать кнопку Зарегистрироваться.
3 - На появившейся странице отказаться от регистрации.
4 - Снова нажать Зарегистрироваться.
**Результат:** Зарегистрироваться уже невозможно, возможно только после полного удаления приложения и установки снова.

**Comment by gentee** [comment]
Исправлено commit #184

**Comment by ylomakin** [comment]
Fixed
