### ISSUE TITLE
Small error when you upgrade your account miner v2.2.3a7

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#185]
1 - Complete all the steps to upgrade to the fifth.
2 - Enter an email, and get an answer that is full pull.
3 - Update and go through all the steps again.
4 - Enter the same email.
**Result:** The error table.
`Sign up In the pool: {"error":"UNIQUE constraint failed: pool_waiting_list.email in query INSERT INTO pool_waiting_list ( email, time, user_id ) VALUES ( ?, ?, ? ) [yuriy.lomakin@gmail.com %!s(int64=1459942335) %!s(int64=2429)] sign_up_in_pool.go:86 -\u003e controllers.(*Controller).SignUpInPool:86 / asm_amd64.s:473 -\u003e runtime.call64:473 / value.go:438 -\u003e reflect.Value.call:435 / value.go:303 -\u003e reflect.Value.Call:303 / (controllers.(*Controller).SignUpInPool : 88)"}`

![06-04-2016 14-41-27](https://cloud.githubusercontent.com/assets/10295842/14315415/b1ff584e-fc05-11e5-820c-e4e7ea398d98.jpg)

1 - Пройти все шаги апгрейда до пятого.
2 - Ввести email, и получить ответ о том, что пулл заполнен.
3 - Обновить и пройти все шаги снова.
4 - Ввести тот же email.
**Результат:** В таблице ошибка.
`Sign up In the pool: {"error":"UNIQUE constraint failed: pool_waiting_list.email in query INSERT INTO pool_waiting_list ( email, time, user_id ) VALUES ( ?, ?, ? ) [yuriy.lomakin@gmail.com %!s(int64=1459942335) %!s(int64=2429)] sign_up_in_pool.go:86 -\u003e controllers.(*Controller).SignUpInPool:86 / asm_amd64.s:473 -\u003e runtime.call64:473 / value.go:438 -\u003e reflect.Value.call:435 / value.go:303 -\u003e reflect.Value.Call:303 / (controllers.(*Controller).SignUpInPool : 88)"}`

**Comment by gentee** [comment]
Fixed in commit #257

**Comment by ylomakin** [comment]
Fixed
