### ISSUE TITLE
I can not do an upgrade to miners (Doogee X5 Android 5.1) v2.2.3a9

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#188]
1 - Download and install the application.
2 - Register a new key.
3 - Go to the section Mining to perform the upgrade account.
4 - Go to a page with a button Get FREE coins. Push it.
![screenshot_2016-04-08-12-40-43](https://cloud.githubusercontent.com/assets/10295842/14380550/b894e6f4-fd88-11e5-82f6-43220990574e.png)
**Result:** Go to the page with the animation blocks, and stuck there. And when the phone is asleep, then at the entrance to get to the Home application.

![screenshot_2016-04-08-12-40-59](https://cloud.githubusercontent.com/assets/10295842/14380556/bcd54b78-fd88-11e5-8a65-9914b947faaa.png)

1 - Скачать и установить приложение.
2 - Зарегистрировать новый ключ.
3 - Перейти в раздел майнинг, чтобы выполнить апгрейд аккаунта.
4 - Переходим на страницу с кнопкой Get FREE coins. Нажимаем её.
**Результат:** Переходим на страницу с анимацией блоков, и там застрянем. И когда телефон засыпает, то при входе в приложение попадаем на Home.

**Comment by gentee** [comment]
Одна из причин исправлена в #192.

**Comment by ylomakin** [comment]
Fixed
