### ISSUE TITLE
You can not transfer the coin to another user v2.2.4a1

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#194]
1 - Start the app and enter the miner's account.
2 - Set the coin to another user.
**Result:** button to send to the network does not respond to a click.

![12-04-2016 14-39-17](https://cloud.githubusercontent.com/assets/10295842/14458853/ded6f302-00bc-11e6-96fc-a805a1d743b3.jpg)

1 - Запустить приложение и войти в аккаунт майнера.
2 - Перевести монеты другому пользователю.
**Результат:** Кнопка отправки в сеть не реагирует на клик.

**Comment by gentee** [comment]
Арбитров не указывал? На самом деле там вернее всего ошибка incorrect arbitrators при отправке есть, но она не показывается. Я внес исправления, нужно посмотреть сейчас. Если это она, то тогда исправлять дальше. Арбитр должен быть обязательным параметром в форме или нет?

**Comment by ylomakin** [comment]
Пробовал и с указанием и без.
Да, ответ приходит incorrect arbitrators

**Comment by ylomakin** [comment]
Раз арбитраж указывается через чекбокс, то наверное не обязателен.

**Comment by ylomakin** [comment]
Fixed
