### ISSUE TITLE
Small bug in the preparation of free coins (Android 4.4.2, Android 5.1) v2.2.4b1

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#203]
При регистрации нового ключа и получении бесплатных монет есть небольшой недочёт, описываю пошагово.
1 - Загружаем приложение, регистрируемся.
1 - После клика на Get FREE coins переходим на страницу где крутятся кирпичи.
2 - Через время осуществляется автоматический переход на страницу выбора типа аккаунта (анонимный или майнер).
3 - При выборе любого попадаем опять на страницу крутящихся кирпичей.
4 - Через время выдаёт ошибку и кнопку Повторить получить бесплатные монеты.
5 - Нажимаю, опять крутятся кирпичи.
6 - Через время попадаем на страницу, где тикают монеты.

**Comment by gentee** [comment]
Я убрал эту страницы с выбором типа аккаунта.

**Comment by ylomakin** [comment]
Fixed
