### ISSUE TITLE
An error occurred while voting

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#215]
Во время голосования при выборе 960-1000% происходит баг:
`Error: [ERROR] incorrect miner_pct (dcparser.(*Parser).VotesComplexFront : 169) [json_data] = {"currency":{"1":[1000,0.00,1,0,0]},"referral":{"first":"30","second":"25","third":"20"},"admin":"0"} [sign] = 820100655894eca0cff2ab11d7132b2c1fef5d5baef3d83655901fa`

**Comment by gentee** [comment]
Вносились изменения, нужно перепроверить.

**Comment by ylomakin** [comment]
Fixed
