### ISSUE TITLE
An error in the transaction table when you add a new amount pledged for the first time (iPad Air) v2.2.4b1

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#217]
When adding the promised first time, after obtaining the status of miners (already with free coins on your account) the transaction is successful, but there is another entry in the table of error.

![img_0032](https://cloud.githubusercontent.com/assets/10295842/14700385/d55edd02-07a7-11e6-87c7-7a1c68b8fc0b.PNG)

При добавлении обещанной впервые, после получения статуса майнера (уже с бесплатными монетами на счету) транзакция проходит успешно, но появляется ещё одна запись об ошибке в таблице.

**Comment by gentee** [comment]
Надо перепроверить, так как вносились изменения по подобному вопросу.

**Comment by ylomakin** [comment]
Fixed
