### ISSUE TITLE
The problem with the addition of a new promised amount in your account (iPad Air) v2.2.4b1

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#218]
1 - Make a upgrade account with free coins in the account.
2 - Add a new promised sum 10DUSD.
3 - To approve the request by five miners,.
**Result:** The application is in pending status for a second day, but on the map in the popup promises to appear immediately after the approval of the five miners.

![20-04-2016 13-15-30](https://cloud.githubusercontent.com/assets/10295842/14700709/0620cc28-07aa-11e6-872e-7f280a314c40.jpg)

1 - Сделать апгрейд аккаунта с бесплатными монетами на счету.
2 - Добавить новую обещанную сумму 10DUSD.
3 - Одобрить заявку пятью майнерами.
**Результат:** Заявка находится в статусе pending уже второй день, но на карте в попапе обещанная появилась уже сразу после одобрения пятью майнерами.

**Comment by c-darwin** [comment]
Чтобы "толкнуть" тр-ию должен прийти голос через сутки. Это не баг, это фича.

**Comment by ylomakin** [comment]
И то что на карте в попапе обещанная появилась раньше чем через сутки, это нормально?

**Comment by c-darwin** [comment]
пусть выводит, не страшно, эта карта просто для красоты, функциональной нагрузки на ней нет

**Comment by ylomakin** [comment]
Ок.
Закрывать тогда эту задачу?
