### ISSUE TITLE
Open console on click Support 2.2.5b1 & scroll

### ISSUE THREAD

**Issue by Hunternnm** [democratic-coin/dcoin-go#221]
Версия 2.2.5b1 при клике на пункт меню Support открывается консоль и всё. win 10 x64.

При небольшом размере окна при раскрытии длинных пунктов меню нижние уходят за пределы видимости без возможности скролла. 
![1](https://cloud.githubusercontent.com/assets/5153607/14731816/750a2130-085d-11e6-8911-51c8c7732b31.jpg)

**Comment by gentee** [comment]
Fixed in commits #296 and #297

**Comment by ylomakin** [comment]
Fixed
