### ISSUE TITLE
Do not enter the new application for approval DRUB v2.2.5b1

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#222]
Do not come to the application for approval of the promised Russian rubles.
Even those accounts that mining ruble.
And for dollars bid came nearly 24 hours later, almost at the very end of the allotted time for voting (not even had time to approve all five miners issued on the third error that voting is finished).

Не приходят заявки на одобрения обещанной в российских рублях.
Даже тем аккаунтам, которые майнят рубль.
А на доллары заявка пришла почти спустя 24 часа, почти под самый конец отведённого времени для голосования (не успел одобрить даже всеми пятью майнерами, на третьем выдало ошибку, что голосование закончено).

**Comment by gentee** [comment]
Проверь еще раз. У меня пришла заявка.

**Comment by ylomakin** [comment]
Fixed
