### ISSUE TITLE
Align on startUp

### ISSUE THREAD

**Issue by Hunternnm** [democratic-coin/dcoin-go#225]
При старте появляются полосы прокрутки. Полагаю, берется размер окна, которое открывается после загрузки программы. Не критично, но почему-то бросается в глаза(не только я заметил). 
![1](https://cloud.githubusercontent.com/assets/5153607/14760769/340ed268-0955-11e6-82b4-5ed127693989.jpg)

**Comment by gentee** [comment]
Fixed in #279

**Comment by ylomakin** [comment]
Fixed
