### ISSUE TITLE
Error Synchronization blockchain when a new version of the application

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#230]
When a change in the core with the release of the new version is the synchronization error when blockchain.
In such cases, enter into the application is not possible, even after the reinstallation application.

При изменении в ядре с выходом новой версии бывает ошибка при синхронизации блокчейнов.
В таких случаях войти в приложение уже не возможно, даже после полной переустановки приложения.

**Comment by c-darwin** [comment]
после полной перестановки старой версии

**Comment by gentee** [comment]
Добавил определение новой версии в synchronization blockchain commit #233.

**Comment by ylomakin** [comment]
Fixed
