### ISSUE TITLE
101% on sync 

### ISSUE THREAD

**Issue by Hunternnm** [democratic-coin/dcoin-go#240]
При синхронизации после запуска неправильно отображаются проценты. У меня вот идет синхронизация, но уже показывает 101%... 
![1](https://cloud.githubusercontent.com/assets/5153607/14934205/2d435168-0eb2-11e6-8da7-9ec5c140d4bd.jpg)

**Comment by c-darwin** [comment]
Это из-за константы в packages/consts.go
// примерный текущий крайний блок
const LAST_BLOCK = 310000 (когда меньше текущего максимального, показывает лишние %)
В новом релизе исправится.
