### ISSUE TITLE
Failed to change the promised amount

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#248]
Нужно лимиты выводить consts.MaxGreen

`"Error: [ERROR] incorrect amount (dcparser.(*Parser).ChangePromisedAmountFront : 67) [type] = 4 [time] = 1462949124 [user_id] = 1021 [promised_amount_id] = 150 [amount] = 200 [sign] = 820100b5dd7689904efa2b5f2d455dcc3743c99bbcc506038bd87d42af2363a5e8fe5ba3346b2"`

**Comment by gentee** [comment]
Fixed in commit #289. Добавил ограничение ввода обещанной суммы по максимальному значению.

**Comment by ylomakin** [comment]
Fixed
