### ISSUE TITLE
Error on the network, will soon be updated

### ISSUE THREAD

**Issue by Hunternnm** [democratic-coin/dcoin-go#251]
При запуске программы пишет ошибку:
![1](https://cloud.githubusercontent.com/assets/5153607/15267030/d538b888-19be-11e6-8d86-2c4935c76578.jpg)
```
2.3.1b2
{}
[{"ban_start":"1463210852","info":"blockId: 317314 / double log_transactions 722f9efc8843e9a11962b879abae0347 (dcparser.(*Parser).CheckLogTx :  816) (dcparser.(*Parser).ParseDataFull :  81)","user_id":"2"},{"ban_start":"1463210913","info":"blockId: 317314 / double log_transactions 722f9efc8843e9a11962b879abae0347 (dcparser.(*Parser).CheckLogTx :  816) (dcparser.(*Parser).ParseDataFull :  81)","user_id":"4"}]
```
С интернетом всё хорошо...

**Comment by Hunternnm** [comment]
Обновился до 2.3.1b5 - картина та же.

**Comment by c-darwin** [comment]
Попробуйте обновиться сейчас, через 5 минут появится кнопка "reload blockchain", её надо нажать.

**Comment by Hunternnm** [comment]
Спасибо, помогло. Только весь процесс занял около 2-х часов... Хотя комп довольно мощный + оптика.
