### ISSUE TITLE
You can not add the promised amounts v2.3.1b8

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#258]
При попытке добавить обещанную сумму выдаёт следующую ошибку:

![16-05-2016 18-26-43](https://cloud.githubusercontent.com/assets/10295842/15294210/f8092254-1b93-11e6-8bb1-cf9ad9811d09.jpg)

**Comment by gentee** [comment]
Это у тебя на старом аккаунте такое?

**Comment by gentee** [comment]
Fixed in commit #259

**Comment by ylomakin** [comment]
Да на всех акаунтах, которые сделаны больше двух-трёх недель назад.
Ок, проверю после комита #259.

**Comment by ylomakin** [comment]
Fixed
