### ISSUE TITLE
Ошибка добавления новой Обещанной суммы

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#26]
**Windows 7 64-bit**

1 - Зайти в приложение и перейти в Майнинг / Мои обещанные суммы
2 - Добавить Новую обещанную сумму (в данном случае добавлял 10 евро)

**Результат:** В таблице Транзакции показывает ошибку
`Error: [ERROR] !$woc (dcparser.(*Parser).NewPromisedAmountFront : 92) [time] = 1455783373 [currency_id] = 23 [sign] = 82010045278f2af306387e5458c96e8f614b17660261bdb1acc1c76cc3052fc1ea3c7b82401119d42c6d025d25de0527cc755cd9c596c91111b9165c587ab0a5f5aa54acf32dac`

![kag7p7nig7wdja](https://cloud.githubusercontent.com/assets/10295842/13137419/9ad8bb08-d629-11e5-930e-aa43faa3ca90.jpg)

**Comment by ylomakin** [comment]
**Релиз v2.1.0a17 (Windows 7)**
Не исправлено.

Сначала вроде добавление прошло нормально
![n2yrzresjnmzva](https://cloud.githubusercontent.com/assets/10295842/13460427/1f251cea-e083-11e5-91a1-4caf45df3a9b.jpg)

Спустя некоторое время обновив страницу - в таблице показана ошибка

`Error: [ERROR] max_other_currencies (dcparser.(*Parser).NewPromisedAmountFront : 101) [time] = 1456921191 [user_id] = 1792 [sign] = 82010064ba4f3a54f776f880d7814063478f07a9a308fd89774c8802c046bedd3cca1625a7c7fd86563d50e3bb6150284ee1cf0adca06f2e67165a435ed86d98`

![gmv6b6ehxz51jm](https://cloud.githubusercontent.com/assets/10295842/13460429/20cd0404-e083-11e5-84d6-a400af585fdf.jpg)

**Comment by c-darwin** [comment]
В первом случае !$woc (dcparser.(*Parser).NewPromisedAmountFront : 92) могло выдать когда не дождавшись завершения модерации самой первой первой суммы стала добавляться новая.
Во втором случае была попытка добавить новую обещанную, хотя лимит max_other_currencies у какой-то из валют не позволял этого сделать

**Comment by ylomakin** [comment]
Не баг, но пока не закрываю.
Когда появятся алерты с сообщениями, тогда закрою.

**Comment by gentee** [comment]
Я сделал следующим образом. Вместо того чтобы отслеживать ошибки потом, лучше запрещать добавление новых обещанных сумм в таких случаях. На данный момент кнопка Добавить обещанные суммы скрывается в следующих случаях. 
* Когда есть необработанная транзакция по обещанным суммам.
* Когда обещанная сумма уже есть, но одобренных сумм еще нет
* Если у какой-то валюты из обещанных уже достигнут предел в max_other_currencies

**Comment by ylomakin** [comment]
Fixed
