### ISSUE TITLE
The button "Get more coins" does not appear immediately v2.3.1b8

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#264]
1 - Download and install the wallet.
2 - Register and login.
3 - Go to the Mining page and click on Get free coins.
4 - Get Verified through social networks.
5 - With the accumulation of the required amount (0.1) or more to put coins in the purse.
**Result:** After receiving the coins on the purse should appear "Get more coins" button, but it does not appear. You will see it in a day or in the accumulation of over 0.1 is not exactly clear.
**Expected Result:** The button "Get more coins" should appear immediately after the receipt of the amount already accumulated in the wallet.

![17-05-2016 15-29-55](https://cloud.githubusercontent.com/assets/10295842/15323085/e4547b54-1c48-11e6-9fb8-6a884c6515f4.jpg)
![17-05-2016 15-30-34](https://cloud.githubusercontent.com/assets/10295842/15323086/e454aef8-1c48-11e6-9515-def02b0a71ae.jpg)

1 - Скачать и установить кошелёк.
2 - Зарегистрироваться и войти.
3 - Перейти на страницу Mining и нажать на кнопку Get free coins.
4 - Пройти проверку через социальные сети.
5 - При накоплении нужной суммы (0,1) или больше положить монеты в кошелёк.
**Результат:** После получения монет на кошелёк должна появится кнопка "Получить больше монет", но она не появляется. Появится она через сутки или при накоплении 0,1 снова, точно не понятно.
**Ожидаемый результат:** Кнопка "Получить больше монет" должна появиться сразу после получения уже накопленной суммы на кошелёк.

**Comment by gentee** [comment]
Fixed in commit #265

**Comment by ylomakin** [comment]
Fixed
