### ISSUE TITLE
When sending Free Coins on purse verified social network v2.3.1b8

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#266]
1 - Download and install the wallet.
2 - Register and login.
3 - Go to the Mining page and click on Get free coins.
4 - Get Verified through social networks.
5 - With the accumulation of the required amount (0.1) or more to put coins in the purse.
**Result:** Status check social network changes to Pending.
**Expected result:** a social network status check and must be YES.

![17-05-2016 15-24-08](https://cloud.githubusercontent.com/assets/10295842/15324680/202289bc-1c50-11e6-8773-58c11f9eaae5.jpg)

1 - Скачать и установить кошелёк.
2 - Зарегистрироваться и войти.
3 - Перейти на страницу Mining и нажать на кнопку Get free coins.
4 - Пройти проверку через социальные сети.
5 - При накоплении нужной суммы (0,1) или больше положить монеты в кошелёк.
**Результат:** Статус проверки социальной сети меняется на Pending.
**Ожидаемый результат:** Статус проверки социальной сети должен так и оставаться YES.

**Comment by gentee** [comment]
Fixed in commit #269

**Comment by ylomakin** [comment]
Fiixed
