### ISSUE TITLE
Нельзя выбрать файл ключа

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#27]
**Samsung Galaxy SM-G350E**
**Android 4.4.2**

1 - Запустить приложение.
2 - Нажать кнопку Войти.
3 - В появившемся диалоговом окне нажать кнопу Выберите ключ.

**Результат:** Ничего не происходит, ключ можно вводить только текстом.

**Ожидаемый результат:** Открывается окно, где можно выбрать файл.

**Comment by ylomakin** [comment]
Fixed

**Comment by ylomakin** [comment]
See issue #78

**Comment by c-darwin** [comment]
Повторить баг не смог.
