### ISSUE TITLE
There replays to check social network v2.3.1b8

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#274]
It is necessary to add a check to the addition of a social network.
If the address is approved, then the second time it did not even miss.
Because it is not clear whether the user has refused, for whatever reason, whether it has decided to make a single address multiple accounts.
Now it is even less remembered, but when will come more applications still can not remember.

Нужно добавить проверку на добавление социальной сети.
Если адрес утверждён, то второй раз его уже не пропускать даже.
Потому что сейчас не понятно, то ли юзеру отказал по какой-то причине, то ли он решил на один адрес сделать себе несколько аккаунтов.
Сейчас это ещё более менее помнится, но когда будет приходить больше заявок, всё не вспомнишь.

**Comment by c-darwin** [comment]
https://github.com/democratic-coin/dcoin-go/commit/038f0f1dc7a46852a8cb9887b13612e19fce4ff9

**Comment by ylomakin** [comment]
Fixed
