### ISSUE TITLE
Button "Reload blockchain" appears just v2.3.2b10

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#275]
When you first start with the block sync pops Error, although the blocks continue to be collected and assembled to the end without any problems.

![19-05-2016 17-14-53](https://cloud.githubusercontent.com/assets/10295842/15396666/bd9b84c8-1de5-11e6-9360-a1d0c412ffc2.jpg)

При первом запуске при синхронизации блоков выскакивает Error, хотя блоки продолжают собираться и собираются до конца без каких-либо проблем.

**Comment by gentee** [comment]
Fixed in commit #276. Увеличил тайм ожидания очередного блока до минуты и если скачка все-таки возобновилась после таймаута, то блок убирается.

**Comment by ylomakin** [comment]
Fixed
