### ISSUE TITLE
Status NO reference at the time of check social network v2.3.2b10

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#280]
1 - Download and install the application.
2 - Sign up and get free coins.
3 - Go check on the social network.
**Result:** While checking a social networking application has not yet been approved or rejected by a miner to display the status of Pending or NO (but not a reference), because you can re-submit a request to this account with a different address.

![20-05-2016 11-34-20](https://cloud.githubusercontent.com/assets/10295842/15422012/d6b607be-1e7e-11e6-9ecf-4799984e48ff.jpg)

1 - Скачать и установить приложение.
2 - Зарегистрироваться и получить бесплатные монеты.
3 - Пройти проверку по социальной сети.
**Результат:** Во время проверки социальной сети, пока заявка не утверждена или отклонена майнерами, выводить статус Pending или NO (но не ссылкой), так как можно повторно отправлять заявку с данного аккаунта с другим адресом.

**Comment by ylomakin** [comment]
**Апдейт:** заявка так и остаётся одна, меняется только линк, больше трёх раз менять тоже нельзя - это хорошо. Но лучше не менять вообще.

**Comment by gentee** [comment]
Fixed in commit #282

**Comment by ylomakin** [comment]
Не совсем всё так.
Вот по порядку сейчас поясню.
1 - Отправляем соц. сеть на проверку.
2 - Пока проверяется другими майнерами, висит статус Pending (проверка длится сутки или больше, всё зависит от голосов и голосовавших, если конечно админ не одобрит/отклонит). При добавлении обещанной так.
![20-05-2016 15-42-54](https://cloud.githubusercontent.com/assets/10295842/15427999/8c7b024e-1ea1-11e6-93b6-b1f2a752b54e.jpg)

3 - Если заявка была отклонена, то появляется снова ссылка NO и уменьшается кол-во попыток.
4 - Если попытки закончились, появляется NO (но не ссылкой).
5 - Если всё ок и заявка прошла одобрение, то как сейчас, выводится YES.

А сейчас получается так - я отправил заявку на проверку и снова могу это сделать, так как появилась ссылка.
![20-05-2016 15-50-20](https://cloud.githubusercontent.com/assets/10295842/15428198/98808202-1ea2-11e6-81ab-3c6120bf4414.jpg)

**Comment by gentee** [comment]
Fixed in commit #283. Попробуй сейчас.

**Comment by ylomakin** [comment]
Сейчас что-то странное совсем.
Кнопки положить в кошелёк вообще нет уже третий день. Сумма 0,4 накапала.
При отправке соц сети статус показан Pending, но адрес не пройдёт, так как уже использовался. В общем совсем всё запуталось.
Возможно потому, что адресу был отказ, но есть ещё попытки.
exists SN - это должно быть только если адрес был принят, но не отклонён.

**Comment by gentee** [comment]
Видимо много вариантов разных получается. Посмотрю у данного юзера. Ошибку exists SN выводить только если адрес уже принят?

**Comment by ylomakin** [comment]
ага, если не принят, то есть ещё попытки.
ну также как и при регистрации майнера, если заявка была отклонена, то есть ещё попытки.

**Comment by c-darwin** [comment]
проблема из-за 		exists, err := p.Single("SELECT user_id FROM users WHERE sn_type = ? AND sn_url_id = ?", p.TxMaps.String["sn_type"], p.TxMaps.String["sn_url_id"]).Int64()
я поправлю

**Comment by ylomakin** [comment]
Fixed
