### ISSUE TITLE
Notifications by email only come when you log in to your account v2.3.2b10

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#281]
1 - Go to Account A.
2 - Send dUSD account B.
**Result:** Notice of availability of sufficient funds to the post office to come. The message came just at the entrance to account B.

1 - Зайти в аккаунт А.
2 - Отправить dUSD аккаунту Б.
**Результат:** Сообщение о получении средств на почту не пришло. Сообщение пришло только при входе в аккаунт Б.

**Comment by gentee** [comment]
Посмотрю как можно перенести проверку на сторону email сервера.

**Comment by gentee** [comment]
Сейчас отслеживание прихода и расхода денег производится на стороне email сервера. Сообщения должны уходить и при закрытой программе.

**Comment by ylomakin** [comment]
Fixed
