### ISSUE TITLE
Incorrect finish trust_shell in Windows 10

### ISSUE THREAD

**Issue by gentee** [democratic-coin/dcoin-go#291]
Dcoin с trust_shell некорректно закрывается на Windows 10. После закрытия остается процесс TrustShell, который при этом сильно загружает процессор. При повторных запусках и закрытиях эти процессы накапливаются и полностью забивают процессор.
![2016-05-26_09-37-51](https://cloud.githubusercontent.com/assets/2069001/15563849/003b0930-2326-11e6-980b-504647fc3770.png)

Начну искать причину.

**Comment by gentee** [comment]
Этот баг похоже появляется только если у нас первый запуск и мы закрываем окно, отказываясь от установки и процесс видимо завершается без вызова thrust.Exit.

**Comment by gentee** [comment]
На самом деле не удается получить постоянное срабатывание данной ошибки. Нужно будет в дальнейшем отслеживать ее появление.

**Comment by gentee** [comment]
Исправления внесены в коммит #312. Нужно будет поотслеживать повторение таких ситуаций.

**Comment by ylomakin** [comment]
Fixed
