### ISSUE TITLE
Empty window on the first run or updating blockchain

### ISSUE THREAD

**Issue by gentee** [democratic-coin/dcoin-go#292]
Иногда при первом запуске или после reload blockchain показывается пустое окно. После обновления оно становится нормальным. Проблема в том, что происходит panic когда мы пытаемся получить GetCommunityUsers для проверки версии не проверяя инициализирована у нас БД или нет (c.dbInit). Иногда БД не успевает инициализироваться.

**Comment by gentee** [comment]
Fixed in commit #293

**Comment by ylomakin** [comment]
Fixed
