### ISSUE TITLE
Doesn't work Transfer funds between accounts v2.3.3b1

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#302]
Перестали пересылаться средства между аккаунтами. Все транзакции получают статус Lost.

![31-05-2016 13-06-32](https://cloud.githubusercontent.com/assets/10295842/15670929/99d5d1de-2730-11e6-811c-1160a22a8f04.jpg)

**Comment by gentee** [comment]
Попробуй еще раз. У меня сейчас нормально прошёл перевод денег.

**Comment by ylomakin** [comment]
Fixed
