### ISSUE TITLE
Unclosed TCP connections

### ISSUE THREAD

**Issue by gentee** [democratic-coin/dcoin-go#316]
В определенных случаях множатся незакрытые соединения. 
![2016-06-08_08-57-15 2](https://cloud.githubusercontent.com/assets/2069001/15883586/e775457c-2d62-11e6-9546-9b0ab0f8a865.png)

**Comment by gentee** [comment]
Причина была в незакрытом resp в controllers/synchronization_blockchain.go
>resp, err := http.Get(blockchain_url)
>if err != nil {
>  	return "", err
>}
>fileSize = resp.ContentLength

**Comment by ylomakin** [comment]
Fixed
