### ISSUE TITLE
Not downloaded Keys

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#319]
На http://pool.dcoin.club/#newUser не скачиваются ключи к реферальной программе, открывается главная страница.
![10-06-2016 10-46-58](https://cloud.githubusercontent.com/assets/10295842/15957632/1499a5d8-2ef9-11e6-9cab-983ae4f8e25b.jpg)

**Comment by gentee** [comment]
Причина найдена и находится на исправлении.

**Comment by gentee** [comment]
Fixed in commit #321

**Comment by ylomakin** [comment]
Fixed
