### ISSUE TITLE
Сообщение сменить node-ключ не исчезает

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#33]
**Web версия, все браузеры**

1 - Сменить node-ключ.

**Результат:** В приложении на windows и андроид сообщение исчезло, в браузерах - нет.

![p276b6wh08ybvm](https://cloud.githubusercontent.com/assets/10295842/13171527/f97cf8c2-d6fb-11e5-8270-a454a7601ee5.jpg)

**Ожидаемый результат:** Сообщение исчезает везде, с какого бы девайса или компьютера не зашли в свой аккаунт.

**Comment by gentee** [comment]
Fixed in commit #263

**Comment by ylomakin** [comment]
Fixed
