### ISSUE TITLE
Отсутствует таблица "Настройка уведомлений" на веб версии

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#34]
**Так выглядит в Windows 7 64-bit**
![52anvnkfgepkma](https://cloud.githubusercontent.com/assets/10295842/13172330/31f76490-d700-11e5-9ed9-be67462d13da.jpg)

**Так выглядит на веб версии**
![823nznwi63vzqm](https://cloud.githubusercontent.com/assets/10295842/13172372/6ac9ad46-d700-11e5-97cf-bdbb61d2be0c.jpg)

**Comment by gentee** [comment]
В каком браузере? Проверьте еще раз, такое ощущение что исправлено. У меня на Windows 10, нормально показывает в Opera и Edge.

**Comment by ylomakin** [comment]
IE 11
Opera 35
Firefox 45
Chrome 49
Edge - bug #107

**Comment by ylomakin** [comment]
Fixed
