### ISSUE TITLE
Error limit promised amount

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#340]
Ситуация:
1 - Был лимит на обещанную 1000.
2 - Лимит изменился (уменьшился) до 100.
3 - После уменьшения, уже установленная 1000 не меняется.
4 - При запросе на обмен, на карте так же показано, что у человека обещанная 1000 и можно её запросить (или минимум 200) при лимите всего лишь 100.

![23-06-2016 10-17-52](https://cloud.githubusercontent.com/assets/10295842/16295079/2ff8c3a2-392d-11e6-93ef-cf192b448ea0.jpg)

Вообще не знаю, на сколько это баг и как логично его поправить.
Теоретически, ну если человек хочет, то уже так пусть и остаётся.
Нужно обдумать варианты, так как считаю что при уменьшении лимита реальный майнер будет не в восторге от автоматического уменьшения обещанной.

**Comment by c-darwin** [comment]
Эта цифра на карте выдается без учета conts.MaxGreen, в реальности при попытке послать запрос на 1000$ произойдет ошибка и он не уйдет в сеть. Надо добавить учет MaxGreen

**Comment by gentee** [comment]
Fixed in commit #342

**Comment by ylomakin** [comment]
Fixed
