### ISSUE TITLE
You can request an exchange in the amount of more than promised

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#345]
При отправке запроса на обмен через прямое указание ID получателя учитывать количество доступных у него обещанных.
Сейчас можно указать ID юзера и 100$, а у него нет такой обещанной.
Нужно слать аякс запрос после ввода user_id и заполнять максимально допустимую обещанную сумму или писать, что у него нет обещанных и запрос нельзя слать.

**Comment by gentee** [comment]
Fixed in commit #346

**Comment by ylomakin** [comment]
Fixed
