### ISSUE TITLE
Ошибка регистрации

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#37]
**Windows 7 64-bit**

**Релиз v2.1.0a13**

1 - Удалить приложение через uninstall, удалить оставшуюся папку программы.
2 - Установить Windows 64 bits (.exe), запустить приложение.
3 - Нажать кнопку Зарегистрироваться.

**Результат:** Ошибка, скрин приложен.

![zrjodons1djdjm](https://cloud.githubusercontent.com/assets/10295842/13181059/dbde9bd0-d733-11e5-8357-31841fe76c0f.jpg)

**Comment by gentee** [comment]
Нужно будет пробовать с новым обновлением
https://github.com/c-darwin/dcoin-go/pull/56

**Comment by ylomakin** [comment]
Не исправлено.
Баг проскакивает после следующих шагов:
1 - Установить приложение и войти.
2 - "Погулять по страницам" и разлогиниться.
После этого уже регистрация не возможна, даже если закрыть приложение и снова запустить.

**Comment by gentee** [comment]
Причина одна и та же с #49. Сейчас кнопка Зарегистрироваться не будет показываться когда регистрация невозможна.

**Comment by ylomakin** [comment]
Fixed
