### ISSUE TITLE
Registration error (Windows 7 64-bit) v2.1.0a14

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#49]
1 - Run the application after all the steps in #48
2 - Click "Sign up"
**Result:** Error.
![e2pwbwjfb86l3m](https://cloud.githubusercontent.com/assets/10295842/13244774/963cc616-da11-11e5-9d96-dcbceb429090.jpg)

1 - Запустить приложение после всех шагов в #48
2 - Нажать кнопку "Зарегистрироваться"
**Результат:** Ошибка.

**Comment by gentee** [comment]
Такая же ошибка после 
1. Установка
2. Переход на Зарегистрироваться
3. Выход

Когда запускаем в следующий раз, то такое же сообщение. Нужно поразбираться.

**Comment by gentee** [comment]
Думаю, что исправлено в https://github.com/c-darwin/dcoin-go/pull/56

**Comment by ylomakin** [comment]
Не исправлено. Смотри #37#issuecomment-195694843

**Comment by gentee** [comment]
Исправлено в коммите #199
Сейчас, когда регистрация невозможна, кнопка Зарегистрироваться не показывается.

**Comment by ylomakin** [comment]
Fixed
