### ISSUE TITLE
You can not upload a photo (Samsung Galaxy SM-G350E Android 4.4.2) v2.1.0a16

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#59]
1 - Download the app from Google Play and install it.
2 - Register and login to your account.
3 - Start the upgrade account.
4 - In the second step, click Select photo
**Result:** Nothing happens.

![screenshot_2016-03-01-14-17-30](https://cloud.githubusercontent.com/assets/10295842/13426925/60a35bde-dfb9-11e5-99ba-921459b8577a.png)

1 - Скачать приложение с Google Play‎ и установить.
2 - Зарегистрироваться и войти в аккаунт.
3 - Начать апгрейд аккаунта.
4 - На втором шаге нажать Select photo
**Результат:** Ничего не происходит.

**Comment by ylomakin** [comment]
Fixed

**Comment by ylomakin** [comment]
Bug no fixed.
See issue #78

**Comment by c-darwin** [comment]
Повторить баг не смог.
