### ISSUE TITLE
Баг при регистрации нового ключа

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#60]
Правил задачу #48
1 - Добавил кнопку Отмена, по клику должна перекидывать на страницу Вход/Регистрация.
2 - Через dc_navigate ('login', "") сделал возврат на страницу Вход/Регистрация.
Результат: По клику на кнопку Отмена перекинуло уже на страницу выбора типа аккаунта, не на страницу Вход/Регистрация. Реализовать удалось только через logout. Получается, что страница уже залогиненая, когда ключ успешно сгенирирован, даже если ему не придуман пароль и он не скачан ещё.

**Comment by gentee** [comment]
Попробуйте обновить файлы с этого pull request https://github.com/c-darwin/dcoin-go/pull/56
Там сейчас ищется свободный ключ только после того, как пользователь нажмет кнопку Скачать.

**Comment by gentee** [comment]
commit https://github.com/c-darwin/dcoin-go/pull/61

**Comment by ylomakin** [comment]
Fixed
