### ISSUE TITLE
Change location (all OS and web) v2.1.0a15

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#64]
1 - Go to the _Mining / My location_
**Result:** There is no auto-detect the user's location. If you change the coordinates of the marker on the map does not change its location. "Next" button is misleading, it would be better called "Save" and make it active only in the event of a change of location.

1 - Перейти на _Mining / My location_
**Результат:** Нет автоопределения местоположения юзера. При изменении координат маркер на карте не меняет своё местоположение. Кнопка "Далее" вводит в заблуждение, лучше было бы назвать "Сохранить" и делать её активной только в случае изменения местоположения.

**Comment by ylomakin** [comment]
**Windows 7**
Баг исправлен, но появился другой.
Не запоминает новое местоположение после передвижения маркера и нажатия Далее.

**Comment by gentee** [comment]
Fixed in commit #198

**Comment by ylomakin** [comment]
Fixed
