### ISSUE TITLE
Bug Mining -> User registration (Windows 7) v2.1.0a17

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#66]
1 - Go to the _Mining / User registration_
2 - Add a new user
![q2kdldxs9wza4a](https://cloud.githubusercontent.com/assets/10295842/13463845/dab9948c-e096-11e5-9218-693d24d21a3c.jpg)
3 - Exit the application and uninstall completely from your computer.
4 - Install the application from scratch and go to _Mining / User registration_
**Result:** Table with referrals disappeared.

1 - Перейти на _Mining / User registration_
2 - Добавить нового юзера
3 - Выйти из приложения и удалить полностью с компьютера.
4 - Установить приложение с нуля и перейти на _Mining / User registration_
**Результат:** Таблица с рефералами пропала.
![vm6595wcx7bm1r](https://cloud.githubusercontent.com/assets/10295842/13463840/d44f5a32-e096-11e5-88bb-66a3d2fac65e.jpg)

**Апдейт: Таблица на web остаётся, на десктопных версиях пропадает. Похоже эта информация держится локально, на сервер не передаётся.**

**Comment by c-darwin** [comment]
При нажатии кнопке "new user" генерируется новая пара ключей (публичный и приватный). Публичный шлется в DC-сеть, после чего в Dcoin рождается новый юзер. Чтобы этот юзер мог получать доступ к своему аккаунту, ему нужен приватный ключ. Приватный ключ храниться на машине, где был сгенерирован.

**Comment by ylomakin** [comment]
Не совсем тогда понимаю логику.
Я зарегистрировал три юзера в разных ОС и на веб
С одним ключом я уже заходил, типа юзер активный уже, добавил ему пароли. В общем с ним работать начал)

Только на веб версии есть такая таблица (третий юзер где-то потерялся совсем)
![dmb1z1din548lr](https://cloud.githubusercontent.com/assets/10295842/13489349/26b234b4-e12f-11e5-9f06-de90f8c304d9.jpg)

На ОС этой таблицы вообще нет
