### ISSUE TITLE
Нет возможности указать местоположение

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#7]
1 - Зайти в аккаунт, используя ключ и пароль.
2 - Выбрать тип аккаунта Майнер.
3 - Дойти до 5-го шага

**Результат:** Предлагают выбрать Ваше местоположение, но на странице ничего кроме карты нет (автоматического определения местоположения также нет).

**Ожидаемый результат:** Указать своё местоположение можно вручную или должно быть автоопределение.

**Comment by c-darwin** [comment]
Автоопределение убрано т.к. хромиум почему-то вылетает. Если кто-то сможет устранить этот баг в хромиуме, будет очень круто.

**Comment by ylomakin** [comment]
Если достаточно для местоположения только страны, то этот шаг лишний выходит, так как в 1-м шаге выбирается страна.

**Comment by c-darwin** [comment]
А это идет подготовка к добавлению обещанной суммы. Т.к. при нескольких десятках тысяч пользователей в одном городе можно будет без комиссий обменять, например, dUSD на $ у ближайшего майнера. А майнера без обещанной суммы быть по идее не должно, иначе зачем он апгрейд аккаунта делал. 
Хотя, по хорошему, указание местоположения можно перенести в другое место (но до добавления обещанной суммы)

**Comment by ylomakin** [comment]
Fixed
