### ISSUE TITLE
Error interface (Samsung Galaxy SM-G350E Android 4.4.2) v2.1.0a19

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#76]
1 - Install the app for the first time.
2 - Register.
3 - When there is a new key registration, minimize the application, and then deploy.
**Result:** appears lower menu, which the user should not see until you go down to your account.

![screenshot_2016-03-04-09-14-35](https://cloud.githubusercontent.com/assets/10295842/13520570/1f78ef7e-e1ea-11e5-900b-517816115ffd.png)

1 - Установить приложение впервые.
2 - Зарегистрироваться.
3 - Когда идёт регистрация нового ключа, свернуть приложение, потом развернуть.
**Результат:** Появляется нижнее меню, которое не должен видеть юзер пока не зайдёт в аккаунт.

**Comment by gentee** [comment]
Исправлено

**Comment by ylomakin** [comment]
Fixed
