### ISSUE TITLE
Bug select key and photo (Samsung Galaxy SM-G350E Android 4.4.2) v2.1.0a19

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#78]
If the application opens through to localhost, then everything works.
If you like the app, all that is connected with the selection of files via a click on the button does not work.

Если приложение открывается через localhost, то тогда всё срабатывает.
Если же как app, всё что связано с выбором файлов через клик на кнопки, не работает.

**Comment by c-darwin** [comment]
повторить баг не смог. версия андроида такая же
