### ISSUE TITLE
Very long time black screen (Samsung Galaxy SM-G350E Android 4.4.2) v2.1.0a19

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#79]
When you run 15-16 seconds of black screen, then White 2-3 seconds, and then the screen will appear with a choice of the type of launch.

При запуске приложения секунд 15-16 чёрный экран, потом 2-3 секунды белый, а потом уже появляется экран с выбором типа запуска.

[logcat.txt](https://github.com/c-darwin/dcoin-go/files/159721/logcat.txt)

**Comment by gentee** [comment]
Такой же черный экран наблюдается при запуске на Android 4.2.2

**Comment by ylomakin** [comment]
Fixed
