### ISSUE TITLE
Оформить странцу

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#8]
1 - Зайти в аккаунт, используя ключ и пароль.
2 - Выбрать тип аккаунта Майнер.
3 - Перейти на 7-й шаг

**Результат:** 
![b177b1880d](https://cloud.githubusercontent.com/assets/10295842/13051585/9f244188-d402-11e5-8bf5-c3aba716c5f3.jpg)

**Ожидаемый результат:** Привести в доступный для понимания вид.

**Comment by c-darwin** [comment]
Я думаю можно этот шаг пропустить (если человек делает апгрейд акка на пуле, т.к. на пуле host уже заполнен)

**Comment by ylomakin** [comment]
Закрываю
