### ISSUE TITLE
Enabled all button during checkout transaction (all OS and web) v2.1.0a19

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#81]
1 - Go to the page My promised amounts.
2 - Change the amount and click the Change button for example.
**Result:** There is a process of checking transactions, all the fields and buttons are active.
**Expected result:** While there is a process of transaction verification, the whole line of the promised sum from which there is a verification process is not available for any operations.

![y2lpkpxinowzp2](https://cloud.githubusercontent.com/assets/10295842/13547803/a31d6b58-e2e8-11e5-8f26-f15dda6b9ea5.jpg)

1 - Зайти на страницу Мои обещанные суммы.
2 - Изменить сумму и нажать к примеру кнопку Изменить.
**Результат:** Пока идёт процесс проверки транзакции, все поля и кнопки активны.
**Ожидаемый результат:** Пока идёт процесс проверки транзакции, вся строка обещанной суммы с которой идёт процесс проверки не доступна ни для каких операций.

**Comment by gentee** [comment]
Буду смотреть.

**Comment by ylomakin** [comment]
Работает как нужно, кроме кнопки Удалить.
Когда её нажимаешь, то перекидывает на пустую страницу и никаких транзакций в таблице нет.

**Comment by gentee** [comment]
А раньше нормально работало? Я в части delete ничего не менял.
И когда обратно возвращаетесь на обещанные суммы, то там он не удаленный остается?

**Comment by ylomakin** [comment]
Неа, сумма не удаляется.

![dr8w4wwfkl9wqa](https://cloud.githubusercontent.com/assets/10295842/13872414/3dbd5d08-ecf3-11e5-9704-a8364121f1ea.jpg)

Вообще когда-то удалялась, но до решения этой задачи уже баг с удалением был.

**Comment by c-darwin** [comment]
@ylomakin когда статус стал rejected?

**Comment by ylomakin** [comment]
@c-darwin  Не обращал внимания, но точно давно, наверное даже больше недели.
В релизе v2.2.3a3 эта сумма удалилась нормально, с блокировкой полей во время проверки транзакции.
Думаю можно закрывать. Или ещё есть недочёты и этот таск в работе?

**Comment by ylomakin** [comment]
Fixed
