### ISSUE TITLE
Failed to change the promised amount (all OS and web) v2.1.0a19

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#82]
1 - Go to the page My promised amounts.
2 - Enter the new amount in the range of permissible and click Change.
**Result:** The amount is not changed, the table transaction error.
`Error: [ERROR] incorrect promised_amount_id (dcparser.(*Parser).ChangePromisedAmountFront : 44) [user_id] = 1792 [promised_amount_id] = 109 [amount] = 100 [sign] = 82010088b843765a5e4e8a5e10766a7956dccc91d5f29e68716691732e8f6b0ab8279c60f7b1fbd6bd75fec10200e3a3`

1 - Зайти на страницу Мои обещанные суммы.
2 - Ввести новую сумму в пределах допустимой и нажать кнопку Изменить.
**Результат:** Сумма не изменена, в таблице транзакций сообщение об ошибке.
`Error: [ERROR] incorrect promised_amount_id (dcparser.(*Parser).ChangePromisedAmountFront : 44) [user_id] = 1792 [promised_amount_id] = 109 [amount] = 100 [sign] = 82010088b843765a5e4e8a5e10766a7956dccc91d5f29e68716691732e8f6b0ab8279c60f7b1fbd6bd75fec10200e3a3`

**Comment by c-darwin** [comment]
Взял

**Comment by c-darwin** [comment]
Баг не критичный. Просто непонятно для юзера что происходит.
[promised_amount_id] = 109
а по (dcparser.(*Parser).ChangePromisedAmountFront : 44) видно, что есть запрос 
SELECT id, currency_id FROM promised_amount WHERE id  =  ? AND status  =  'mining' AND currency_id > 1 AND del_block_id  =  0 AND del_mining_block_id  =  0
Смотрим 109-ю:
sqlite> SELECT id, currency_id, del_mining_block_id, del_block_id, status FROM promised_amount where id=109;
109|23|0|0|rejected
rejected, а должно быть mining, чтобы можно было менять сумму

**Comment by ylomakin** [comment]
Всё таки что-то не то.
`Error: [ERROR] incorrect promised_amount_id (dcparser.(*Parser).ChangePromisedAmountFront : 44) [sign] = 82010028b91e8d301e8addd4897c0e46976b8a6d0bcf892448a712f54ca31f8c92f12ce0a6de64a143ad03578fb06a53ff11782ab7c13db3aeacc32edf4a2199c0545a089c275704fc9f54cd10d`

**Comment by ylomakin** [comment]
Закрываю.
С появлением о неправильных действиях такого бага случится не должно.
