### ISSUE TITLE
Failed to delete the promised amount (Windows 7) v2.1.0a19

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#83]
1 - Go to the page My promised amounts.
2 - Press the Delete button for any of the promised amount.
**Result:** Transition go to a blank page, the amount is not removed, the table does not commits.

1 - Зайти на страницу Мои обещанные суммы.
2 - Нажать кнопку Удалить для любой обещанной суммы.
**Результат:** Осуществляется переход на пустую страницу, сумма не удаляется, в таблице транзакций ничего не фиксируется.

**Comment by c-darwin** [comment]
Не смог повторить. нажимаю "удалить", пишет, что тр-ия ушла в DC-сеть и всё норм.

**Comment by ylomakin** [comment]
Fixed
