### ISSUE TITLE
Checking the applicant miners (Windows 7) v2.1.0a19

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#91]
1 - Go to the Account (miner)
2 - Go to the task that appears (page challenger Checking the miners)
3 - Click Edit.
**Result:** Error.
`{"error":"template: template:22:107: executing \"changeCountryRace\" at : error calling eq: incompatible types for comparison (controllers.makeTemplate : 452) (controllers.(*Controller).ChangeCountryRace : 29)"}`
![e2pwbwjfbbgy4m](https://cloud.githubusercontent.com/assets/10295842/13571742/7bfeabca-e47f-11e5-9100-efcc7f863124.jpg)

1 - Зайти в аккаунт (майнер)
2 - Перейти на появившееся задание (страница Проверка претендента в майнеры)
3 - Нажать ссылку Изменить.
**Результат:** Ошибка.
`{"error":"template: template:22:107: executing \"changeCountryRace\" at : error calling eq: incompatible types for comparison (controllers.makeTemplate : 452) (controllers.(*Controller).ChangeCountryRace : 29)"}`

**Comment by gentee** [comment]
Исправлено в commit #235. Осталось внести изменения по накладыванию заданного фильтра на поиск.

**Comment by gentee** [comment]
Добавлен фильтр на указанные страну и расу при одобрении новых майнеров, commit #236

**Comment by ylomakin** [comment]
Fixed
