### ISSUE TITLE
Not valid data on the page "Checking the applicant in the miners" (Windows 7) v2.1.0a19

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#92]
1 - Go to the Account (miner)
2 - Go to the task that appears (page challenger Checking the miners)
**Result:** In the "When searching for a country is taken into account," contains another country (I pointed out Ukraine) and the race is empty (nothing written).

![ea4nxnwidj7kwm](https://cloud.githubusercontent.com/assets/10295842/13571819/deb046de-e47f-11e5-9308-b8eacdb2928c.jpg)

1 - Зайти в аккаунт (майнер)
2 - Перейти на появившееся задание (страница Проверка претендента в майнеры)
**Результат:** В строке "При поиске учитывается страна:" указана другая страна (я указывал Украина) и раса пустая (ничего не написано).

**Comment by gentee** [comment]
Fixed in commit #229

**Comment by ylomakin** [comment]
Сейчас показывает ALL, так и должно быть?

![23-06-2016 12-05-47](https://cloud.githubusercontent.com/assets/10295842/16297775/eea69ec0-393a-11e6-9e8c-b55381d7ff6d.jpg)

**Comment by gentee** [comment]
Если не выбраны фильтры, то так и должно показываться All.

**Comment by ylomakin** [comment]
А фильтры и не выбираются сейчас.
Этого шага нет же уже?
Или я что-то не допонял?

**Comment by gentee** [comment]
Что, когда нажимаешь на Change, то не переходишь никуда что ли?

**Comment by ylomakin** [comment]
Не, ну при проверке я могу поменять.
Но по идее это должен указывать отправитель заявки?
Как считаешь?

**Comment by c-darwin** [comment]
Страна и раса нужны для того, чтобы азиатам не показывались европейцы, т.к. мы для них на одно лицо. Проверяющий может изменить страны и расы тех, кого желает проверять.

**Comment by ylomakin** [comment]
Понял, тогда закрываю.
