### ISSUE TITLE
Bug upgrade to miner (Windows 10) v2.1.0a22

### ISSUE THREAD

**Issue by ylomakin** [democratic-coin/dcoin-go#97]
1 - Go to the Mining / Upgrade to miner
2 - To reach the 6th step
3 - Enter your e-mail and click Next
**Result:** Nothing happens.

![rmzkbk6uw7ryd2](https://cloud.githubusercontent.com/assets/10295842/13638186/d213f4d0-e613-11e5-8c87-cdd2b59f7665.jpg)

1 - Перейти на Mining / Upgrade to miner
2 - Дойти до 6-го шага
3 - Ввести свой e-mail и нажать Далее
**Результат:** Ничего не происходит.

**Comment by c-darwin** [comment]
Нужна инфа из консоли браузера

**Comment by ylomakin** [comment]
Ну вообще это в установленной программе.
Но сейчас попробую это сделать на пулле в этой же ОС.

**Comment by ylomakin** [comment]
На пуле шаг с видео не работает, страница пустая.
Ругается на Google Map
Скрин
![yme191zizv6p8m](https://cloud.githubusercontent.com/assets/10295842/13696271/fb570a5c-e76d-11e5-9623-7c08cc5cbcc7.jpg)

**Comment by c-darwin** [comment]
взял

**Comment by ylomakin** [comment]
То же самое и в Ubuntu 15.10.
Подозреваю, что это везде.

**Comment by c-darwin** [comment]
происходит из-за того, что 
		if coord, err := geolocation.GetLocation(); err == nil {
			geolocationLat = fmt.Sprintf("%.6f", coord.Latitude)
			geolocationLon = fmt.Sprintf("%.6f", coord.Longitude)

			fmt.Printf("others lat: %s\nlng: %s", geolocationLat, geolocationLon)
		}
coord может  быть пустым и coord.Latitude с паникой выкидывает nill pointer

**Comment by LincolnFaradey** [comment]
https://github.com/democratic-coin/dcoin-go/commit/f6a31b566dca1c3c683d8eda2db103d8ba804e44

**Comment by c-darwin** [comment]
@LincolnFaradey, не исправлено, coord возвращает <nil> без err и дальше идет обращение к coord.Latitude

**Comment by LincolnFaradey** [comment]
https://github.com/democratic-coin/dcoin-go/commit/778f7422d15d33661f6e7420736ce72b9301d1da

try one more time

**Comment by ylomakin** [comment]
Fixed
